# Generated by Django 4.2.6 on 2023-10-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'В обработке'), ('CONFIRMED', 'Подтвержден')], default='IN_PROGRESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CARD', 'Карта'), ('CASH', 'Наличные')], default='CARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Оплачен'), ('IN_PROGRESS', 'В обработке'), ('DECLINED', 'Отменен')], default='IN_PROGRESS', max_length=50),
        ),
    ]
